version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - ferdinandforgaard
  ignore:
  - dependency-name: dns-packet
    versions:
    - 1.3.4
