import {
  teal,
  cyan,
  blue,
  pink,
  deepPurple,
  lime,
  amber,
  deepOrange,
  red,
  green,
  yellow,
  grey,
  orange,
  lightGreen,
  lightBlue,
  purple,
  indigo,
  blueGrey,
  brown,
} from '@mui/material/colors';

const Colors = {
  red: red[500],
  pink: pink[500],
  purple: purple[500],
  deepPurple: deepPurple[500],
  indigo: indigo[500],
  blue: blue[500],
  lightBlue: lightBlue[500],
  cyan: cyan[500],
  teal: teal[500],
  darkTeal: teal[700],
  green: green[500],
  lightGreen: lightGreen[500],
  lime: lime[500],
  yellow: yellow[500],
  amber: amber[500],
  orange: orange[500],
  deepOrange: deepOrange[500],
  brown: brown[500],
  grey: grey[500],
  lightGrey: grey[300],
  hoverGrey: 'rgba(0, 0, 0, 0.08)',
  blueGrey: blueGrey[500],
  black: 'black',
  white: '#fff',
};

export default Colors;
