# This workflow will do a clean install of node dependencies, run tests and build the source code

name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
    inputs:
      args:
        description: 'Jest CLI args'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js (v14)
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test:ci ${{ github.event.inputs.args }}
      
    - name: Build source code
      run: npm run build
