name: "Combine Dependabot PRs"

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:

jobs:
  combine-prs:
    if: github.ref == 'refs/heads/dependabot/updates'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: maadhattah/combine-dependabot-prs@main
        with:
          branchPrefix: "dependabot/npm_and_yarn"
          mustBeGreen: false
          combineBranchName: "dependabot/combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "dependabot/updates"
          openPR: true
