name: Dependabot-sync
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  pull-request:
    name: Open PR to dependabot/updates
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      output1: ${{ steps.openPr.ouputs.pr_url }}
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: pull-request
        id: openPr
        run: echo 'pr_url = gh pr create --title "Pulling ${{ github.ref }} into dependabot/updates" --head "master" --body "*Automated PR*" --base "dependabot/updates"' >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ needs.openPr.outputs.pr_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-test:
    if: ${{ 1 == 2 }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo skipping