name: Dependabot-sync
on:
  pull_request:
    branches:
      - master
    types:
      - closed
  merge_group:

  workflow_dispatch:

jobs:
  pull-request:
    if: github.event.pull_request.merged == true
    name: Open PR to dependabot/updates
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: pull-request
        id: openPr
        run: |
          pr_url=$(gh pr create --title "Pulling ${{ github.ref }} into dependabot/updates" --head "master" --body "*Automated PR*" --base "dependabot/updates") 
          echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ steps.openPr.outputs.pr_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
