name: Dependabot-sync

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  pull-request:
    name: Open PR to dependabot/updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - name: pull-request
        id: open-pr
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit$* }
          gh_pr_up --base 'dependabot/updates'
          gh_pr_up --title 'Pulling ${{ github.ref }} into dependabot/updates' --body '*Automated PR*'
        env:
          PR_URL: ${{ steps.open-pr.outputs.pr_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ steps.open-pr.outputs.pr_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-test:
    if: ${{ 1 == 2 }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo skipping
