# This workflow will build the source code using node and then publish a package to NPM when merging PR to master.
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches:
    - master

jobs:
  publish-npm:
    # this job will only run if the PR has been merged or if job is triggered manually
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm version major --ignore-scripts
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

