name: Release

on:
  push:
    branches:
      - master
      - 'feature/**'
    paths:
      - 'src/**'
      - 'package*'
      
  workflow_dispatch:
    inputs:
      args:
        description: 'CLI arguments'
        required: false
        default: ''
      
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: npm
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npx semantic-release ${{ github.event.inputs.args }}
