# This workflow will do a clean install of node dependencies and run tests

name: Renovate-test

on:
  pull_request:
    branches:
      - 'renovate/updates'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'

  run-test:
    if: ${{ github.actor == 'renovate' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (v14)
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: Install dependencies
        run: npm ci --no-scripts

      - name: Run tests
        run: npm run test:ci
