# This workflow will do a clean install of node dependencies and run tests

name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.*'
      - '.*/**'
      - '*.md'

  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      args:
        description: 'Jest CLI args'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js (v20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci --no-scripts

      - name: Run tests
        run: npm run test:ci ${{ github.event.inputs.args }}
